# Generated by Django 2.0.5 on 2019-04-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSongDownloadTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('task_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_song_download_track',
            },
        ),
    ]
